### ISSUE TITLE
TLib Forge Startup Crash

### ISSUE THREAD

**Issue by SugarDaddii** [t2pellet/strawgolem#140]
https://pastebin.com/yAZ9y6xS

**Comment by burghenby** [comment]
Confirming the issue (seen below) but was able to load mod and have it function in-game with beta.4 from Curseforge.

![image](https://github.com/t2pellet/strawgolem/assets/158222215/98603fe7-fcc5-4150-ab85-e8b3d1a095df)

**Comment by RainbowPangolin** [comment]
I get the exact same error. Looking through [TenzinLibForge.java](https://github.com/t2pellet/tlib/blob/77a4eedb0322ab03c47c56d75122cb0bce7dd01b/Forge/src/main/java/com/t2pellet/tlib/TenzinLibForge.java), it seems like this error happens when `register(String id, TLibForgeMod mod)` is called before `initialSetup()` runs.

**Comment by RainbowPangolin** [comment]
Turns out it's related to the dependency lists in [mods.toml](https://github.com/t2pellet/strawgolem/blob/1.19-rewrite/forge/src/main/resources/META-INF/mods.toml). 

This block:

`[[dependencies.strawgolem]]
modId = "tlib"
mandatory = true
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"`

Should look like:

`[[dependencies.strawgolem]]
modId = "tlib"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"`

**Comment by t2pellet** [comment]
updated to be "AFTER" in mods.toml for newest release 2.1.0-alpha.

lmk if this fixes it!
