### ISSUE TITLE
Golems just die after 1 day with -1 lifespan

### ISSUE THREAD

**Issue by Rychlas** [t2pellet/strawgolem#25]
Just like in the title, whenever I set their lifespan to -1 in the config, they spawn with "<1 day of lifetime" and die after one day.

**Comment by Rychlas** [comment]
Ah wait, I just now realised. It could be because I feed them wheat. 
They spawn dirty and stinky, to fix them I fed them, and maybe that broke them?
Anyway, if that's an issue, can we have a config to make them spawn with normal looks?

Thanks for the great mod, mate. I love it. It's really cute and great early game.

**Comment by t2pellet** [comment]
The visual glitch is a known issue with the forge versions. Should be fixed in the fabric alphas, and will be fixed the next forge release.

My current paradigm is to just continue working on fabric until all the new features are completed, then port them to forge and do a forge release.

Should have something on forge by next week if all goes well.

In the meantime, instead of -1 try setting the lifespan to  2147483646. This should give them a lifespan of roughly 200 years.

Thanks for the kind words :)
