### ISSUE TITLE
Golems just stand around despite fully grown crops.

### ISSUE THREAD

**Issue by Nupper** [t2pellet/strawgolem#59]
![2021-10-29_22 53 19](https://user-images.githubusercontent.com/6026902/139505709-e8776474-b4c3-47b0-a379-3f45732b39fe.png)

**Comment by konrad-parada** [comment]
Same issue
Mod version: strawgolem-1.10-beta-5
Game version: 1.17.1 Fabric

**Comment by t2pellet** [comment]
What are your config settings?

**Comment by t2pellet** [comment]
The golem on the left appears to be sitting down, its hungry and you haven't fed it.

**Comment by mortuusars** [comment]
I'm playing "Create: Above and Beyond" modpack, config seems to be default. But golems just stand in one spot holding the item. Hwyla installed - no "Hunger: Starving" is displayed, and giving them apples does nothing (they do follow me though).

I've tried to specify the chest by shift clicking but this does not seem to work either.

**Comment by t2pellet** [comment]
@mortuusars Your issue is separate from the one pictured above - where the golems are clearly sitting down (notice how you can't see their legs).

Beyond that, this issue is for 1.17, your modpack is in 1.16.

Please make a separate ticket, as I'll be closing this one, since it isn't actually an issue.
