### ISSUE TITLE
1.18.2 - Waila error

### ISSUE THREAD

**Issue by itsdinkd** [t2pellet/strawgolem#81]
**Game Info**
Game Version :
Mod Version :
Mod Loader :

**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

```java
[20May2022 21:13:45.785] [Worker-Main-3/ERROR] [Waila/]: Error loading plugin at com.t2pellet.strawgolem.client.compat.ForgeCompatHwyla
java.lang.NoSuchMethodError: 'void mcp.mobius.waila.api.IRegistrar.addComponent(mcp.mobius.waila.api.IEntityComponentProvider, mcp.mobius.waila.api.TooltipPosition, java.lang.Class)'
	at com.t2pellet.strawgolem.client.compat.CompatHwyla.register(CompatHwyla.java:20) ~[Strawgolem-forge-1.18.2-2.0.0a2.jar%23316!/:2.0.0a2]
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:114) ~[Jade-1.18.2-5.1.0.jar%23203!/:5.1.0]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.19.jar%23362!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.19.jar%23361!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by t2pellet** [comment]
**Game Info**
Game Version :
Mod Version :
Mod Loader :

These fields are part of the template for a reason. Fill them out.

**Comment by t2pellet** [comment]
Closed due to inactivity

**Comment by itsdinkd** [comment]
> Fill them out.

See, I was going to give your mod a chance again in one of the most downloaded fabric packs but then you had to say this, and of course the cluster of issues it has. Word of advice, don't be a smart ass and tell people what to do. It doesn't hurt to use the word **Please**. I nor anyone else owes you nothing.

**Comment by t2pellet** [comment]
Don't expect me to be magically able to solve your issue when you consistently fail to provide the prerequisite information I'd need to even be able to reproduce it. The fields with required information were literally all there in the issue template. If you're submitting an issue and expecting me to be able to fix it, the bare minimum you could do is fill out the prerequisite fields.

Release versions of the mod have always been stable, you've always been interacting with alpha/beta releases, so yes, a "cluster of issues" is to be expected. The bigger question is why you're even trying to put an alpha build of a mod into "one of the most popular fabric packs".

Since you've consistently failed to give me information I need in any of the issues you've created, let me explain why it's important. Every issue you've created I've been completely unable to reproduce. For example, this issue:
![image](https://user-images.githubusercontent.com/4323034/173094789-c74befe7-b3e4-4ba5-a839-705e6716ddbe.png)
That's a screenshot of the latest CurseForge strawgolem build running just fine with WTHIT.
- Game Version: 1.18.2
- Mod Version: 2.0.0a3
- Mod Loader: Fabric
- WTHIT Version: 4.10.3

Try and run this yourself with the following versions, and you'll see, nothing happens. Me having to go out of my way to test a half-dozen different combinations, only for none of them to reproduce your issue is a colossal waste of time for me. 
So I'm not going to politely beg for you to provide me with the bare minimum prerequisite information I need to reproduce and fix your issues. If there's a lack of respect here, it's a lack of respect on **your** part for **my** time. I work on this mod on my free time, the least you can do is fill out the issue template when you're submitting an issue. So, au contraire mon ami, **I** owe you nothing.

**Comment by itsdinkd** [comment]
> First off, release versions of the mod have always been stable, you've always been interacting with alpha/beta releases, so yes, a "cluster of issues" is to be expected. The bigger question is why you're even trying to put an alpha build of a mod into "one of the most popular fabric packs".
> 
> More importantly, don't expect me to be magically able to solve your issue when you consistently fail to provide the prerequisite information I'd need to even be able to reproduce it. Let me try and explain why. I've consistently been unable to reproduce any of your submitted issues. Lets take this one for example. ![image](https://user-images.githubusercontent.com/4323034/173094789-c74befe7-b3e4-4ba5-a839-705e6716ddbe.png) That's a screenshot of the latest CurseForge strawgolem build running just fine with WTHIT.
> 
>     * Game Version: 1.18.2
> 
>     * Mod Version: 2.0.0a3
> 
>     * Mod Loader: Fabric
> 
>     * WTHIT Version: 4.10.3
> 
> 
> Try and run this yourself with the following versions, and you'll see, nothing happens. Me having to go out of my way to test a half-dozen different combinations, only for none of them to reproduce your issue is a colossal waste of time for me. If there's a lack of respect here, it's a lack of respect on **your** part for **my** time. I work on this mod on my own free time, for nothing in return. So, au contraire mon ami, **I** owe you nothing.
> 
> If you're submitting an issue and expecting me to be able to fix it, the bare minimum you could do is fill out the prerequisite fields.

You do not need to go out of your way to solve anything. I completely understand that I failed to put in the version, however, you don't need to tell me what to do. All I am saying is next time say please if you want to tell someone what to do. you are 100% right, you need the version. I am not mad at the fact that you need that, I need that as well when people report issues. However, I am not an asshole about it. 

Take care, best of luck
